// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATo4Pe8rpAIxVSkHM0DmQjH17VpReo6Mg',
    appId: '1:305937213670:web:e09acfcf26d04de2417327',
    messagingSenderId: '305937213670',
    projectId: 'decora-8da7b',
    authDomain: 'decora-8da7b.firebaseapp.com',
    storageBucket: 'decora-8da7b.firebasestorage.app',
    measurementId: 'G-XL1LS2D82V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYl3guaLmMEsAxRnCK7vKG64v-Z0HhWEk',
    appId: '1:305937213670:android:ecfe969e4421035d417327',
    messagingSenderId: '305937213670',
    projectId: 'decora-8da7b',
    storageBucket: 'decora-8da7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_G_vuZ4HSGdcLB_yXujPH2SQiivtzHkU',
    appId: '1:305937213670:ios:4538c81a258ad2dc417327',
    messagingSenderId: '305937213670',
    projectId: 'decora-8da7b',
    storageBucket: 'decora-8da7b.firebasestorage.app',
    iosBundleId: 'com.example.decora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_G_vuZ4HSGdcLB_yXujPH2SQiivtzHkU',
    appId: '1:305937213670:ios:4538c81a258ad2dc417327',
    messagingSenderId: '305937213670',
    projectId: 'decora-8da7b',
    storageBucket: 'decora-8da7b.firebasestorage.app',
    iosBundleId: 'com.example.decora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATo4Pe8rpAIxVSkHM0DmQjH17VpReo6Mg',
    appId: '1:305937213670:web:ba4eed0726cfe9ce417327',
    messagingSenderId: '305937213670',
    projectId: 'decora-8da7b',
    authDomain: 'decora-8da7b.firebaseapp.com',
    storageBucket: 'decora-8da7b.firebasestorage.app',
    measurementId: 'G-YHH1ESKBCC',
  );
}
